Repository therungg/therun-frontend, pull requests merged in 2024-07, with the labels that each got.

#266 Rewrite global search component
  package-lock.json
  package.json
  src/components/css/Search.module.scss
  src/components/search/autocompletion.tsx
  src/components/search/find-user-or-run.ts
  src/components/search/fuzzy-match-highlight.tsx
  src/components/search/global-search.tsx
  src/components/search/use-aggregated-results.tsx
  src/components/search/use-fuzzy-search.tsx
  src/components/topbar.tsx
  src/styles/bootstrap/_utilities.scss
Labels: UX/UI

#268 Update search to reduce rerenders
  src/components/search/fuzzy-match-highlight.component.tsx
  src/components/search/fuzzy-match-highlight.tsx
  src/components/search/global-search.component.tsx
  src/components/search/global-search.tsx
  src/components/search/search-input.component.tsx
  src/components/search/search-results-panel.component.tsx
  src/components/search/use-fuzzy-search.tsx
  src/components/topbar.tsx
Labels: enhancement, refactor

#274 Remove query parameter always being shown
  src/components/search/global-search.component.tsx
Labels: bug
